name: pre-commit
on:
  workflow_call: # Ermöglicht die Wiederverwendbarkeit in anderen Repositories
jobs:
  test:
    runs-on: docker
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4.1.6

      - name: Greet Someone
        run: echo "Hello guys"
